const fs = require('fs');
const minify = require('html-minifier').minify;
const critical = require('critical');
const files = ['./index.html'];

files.forEach(e=>{
	setTimeout(()=>{

		critical.generate({
			inline: true,
			base: './',
			src: e,
			dest: e,
			minify: true,
		});

		fs.writeFileSync(e, minify(fs.readFileSync(e, 'utf8'), {
			caseSensitive:false,
			collapseBooleanAttributes:true,
			collapseInlineTagWhitespace:false,
			collapseWhitespace:true,
			conservativeCollapse:false,
			decodeEntities:true,
			html5:true,
			includeAutoGeneratedTags:false,
			keepClosingSlash:false,
			minifyCSS:true,
			minifyJS:true,
			preserveLineBreaks:false,
			preventAttributesEscaping:false,
			processConditionalComments:true,
			removeAttributeQuotes:true,
			removeComments:true,
			removeEmptyAttributes:true,
			removeEmptyElements:false,
			removeOptionalTags:true,
			removeRedundantAttributes:true,
			removeScriptTypeAttributes:true,
			removeStyleLinkTypeAttributes:true,
			removeTagWhitespace:true,
			sortAttributes:true,
			sortClassName:true,
			trimCustomFragments:true,
			useShortDoctype:true,
		}));

	}, 0);
});